src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Statement__c</fullName>
        <label>Invoice Statement</label>
        <referenceTo>Invoice_Statement__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items_old</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Sold__c</fullName>
        <label>Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public  static Invoice_Statement__C createOneInvoiceStatement ( boolean withLineItem) {
     // create one invoice statement record
       Invoice_Statement__C testInvoice = createInvoiceStatement();
        if (withLineItem ) {
        // create merchant line item
           Merchandise__c m = createMerchandiseItem(' Orange juice');
        // add aline item and associate it with the invoice statement
           AddLineItem(testInvoice,m);
        }
        return testInvoice;
    }
// Helper methods
    private static Merchandise__c createmerchandiseItem ( string merchName) {
    Merchandise__c m = new Merchandise__c(
        Name = merchName,
        Description__c = 'Fresh Juice',
        price__c = 2,
        Total_Inventory__C = 1000);
        insert m;
        return m;
        }
        
        private static Invoice_statement__c createInvoiceStatement () {
        invoice_Statement__c inv = new Invoice_Statement__c ( Description__c = 'Test Invoice');
        insert inv;
        return inv;
        }
        
        private static Line_Item__c AddLineItem (Invoice_statement__c inv, Merchandise__c m) {
        Line_Item__c lineItem = new Line_Item__C (
            					Invoice_Statement__c = inv.Id,
            					Merchandise__C = m.id,
            					Unit_Price__c = m.price__C,
            					Units_Sold__c = (double) (10*Math.random()+1));
            insert lineItem;
            return lineItem;
        }
}